version: 0.2

phases:
  install:
    java: corretto8
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn  clean package 
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - 
  discard-paths: yes 